### PR TITLE
Replace README image paths with project paths for multi project repos

### LINKED ISSUE #193: Images breaking (just for multi?)
Images are not working for e.g.

https://kitspace.org/boards/github.com/eulerlab/open-visual-stimulator/boards/mosfet_circuit/

- is: `https://raw.githubusercontent.com/eulerlab/open-visual-stimulator/master/mofset_circuit_rendering.png?raw=true`
- should be: `https://raw.githubusercontent.com/eulerlab/open-visual-stimulator/master/boards/mosfet_circuit/mofset_circuit_rendering.png?raw=true`

I believe it's an issue with READMEs not being processed correctly for `multi`. @SDBowen can you take a look at it?

### PR DESCRIPTION
**Pull request by SDBowen**
README images not correctly getting processed when they are from a repository with multiple projects.

Corrected this by getting the image filenames and building the correct path using the project path in the Kitspace yaml.

My testing was limited, but it seems to be working for me while playing around with the dev environment projects.

fixes #193

### CODE REVIEW

**Comment by kasbah** [comment]
Hey, the branch name [doesn't work with our preview.kitspace.org deploys](https://travis-ci.org/kitspace/kitspace/builds/591681822#L4275). I mirrored it to `multi-repo-image-breaking` so push to that if you want to preview to http://multi-repo-image-breaking.preview.kitspace.org (which is [building now](https://travis-ci.org/kitspace/kitspace/builds/591700764)). 

I am guessing you tried adjusting the `url` here like you had mentioned? https://github.com/kitspace/kitspace/blob/1102295d99ddf6cd94cd5fb52a313b2914af9465/tasks/page/makeReadme.js#L29

**Comment by SDBowen** [comment]
Yes, I tried that approach first, but seems the URL just got truncated
after passing through the marky library. Was quite aggravating!

File: tasks/page/makeReadme.js [hunk 1]
```diff
@@ -60,3 +72,14 @@ function escapeRegExp(string) {
 function addSpacing(string) {
   return string.replace(/[^ `](`[^\`].*?`)/g, ' $1')
 }
+
+function correctImagePaths(string, projectPath) {
+  const imagePaths = /(\()(.+?(\.png|\.jpg|\.gif|\.jpeg|\.bmp))/g
```
Comment (kasbah) [inline tasks/page/makeReadme.js]: I think we have some doubling up of this logic [here](https://github.com/kitspace/kitspace/blob/2b56d4d29c87b73a24fa985a922c3bfbea3f30db/tasks/page/makeReadme.js#L47) (also, I think yours is case sensitive). Can you condense these into one?

Comment (kasbah) [reply tasks/page/makeReadme.js]: Thinking about it some more, it makes me feel uneasy how this is matched. Could we do it on html img elements post-processing instead? It's also Github specific and we aren't checking for that anywhere?

**Comment by kasbah** [comment]
Does seem to work for these: http://multi-repo-image-breaking.preview.kitspace.org/boards/github.com/eulerlab/open-visual-stimulator/boards/mosfet_circuit/

**Comment by SDBowen** [comment]
Yeah, I thought about the GitHub issue as well.

I will make some changes to cover that and move the match to html.

**Comment by kasbah** [comment]
Cool, I am not 100% sure html is the way to go. It was just a thought. Definitely should be combined with the existing processing of image links though.

File: tasks/page/makeReadme.js (hunk 1 above)
Comment (SDBowen) [reply tasks/page/makeReadme.js]: Going to get this merged this week!

I improved the regex matching: https://regex101.com/r/XcdAeP/2
Think this is strong enough?

Not exactly sure how to combine the two you highlighted above. One is checking for the GitHub direct links that include `/blob/master` and the second checking a repo path.

**Comment by SDBowen** [comment]
Pushed an update to both branches. :ok_hand:

File: tasks/page/makeReadme.js [hunk 2]
```diff
@@ -10,40 +10,49 @@ const converter = new htmlToJsx({createClass: true, outputClassName: 'Readme'})
...
-    let markdown = addSpacing(contents)
+    let markdown = ''
+
     if (path.extname(readme).toLowerCase() === '.rst') {
       markdown = rst2mdown(contents)
+    } else {
+      markdown = contents
     }
+
+    if (info.repo.includes('github')) {
```
Comment (kasbah) [inline tasks/page/makeReadme.js]: This would match e.g. `https://bitbucket.com/foo/my-github-import`

File: tasks/page/makeReadme.js (hunk 1 above)
Comment (kasbah) [reply tasks/page/makeReadme.js]: Thanks for your effort! I think we should use one regex for finding image paths, and then another to check for `/blob/master`. It makes it easier to add image types later on.

File: tasks/page/makeReadme.js [hunk 3]
```diff
@@ -53,10 +62,24 @@ if (require.main !== module) {
...
   return string.replace(/[^ `](`[^\`].*?`)/g, ' $1')
 }
+
+// replace blob image urls with raw image urls, they don't work outside of github
+function replaceImageUrls(string) {
+  const imageUrl = /(https:\/\/github\.com\/.*?\/)(blob)(\/master\/.*?.(:?png|jpeg|jpg|gif|bmp))/gi
+
+  return string.replace(imageUrl, '$1raw$3')
+}
+
```
Comment (kasbah) [inline tasks/page/makeReadme.js]: Can we have comment here explaining this please.

**Comment by kasbah** [comment]
Seems to be replacing them incorrectly right now. 

image

http://multi-repo-image-breaking.preview.kitspace.org/boards/github.com/eulerlab/open-visual-stimulator/boards/mosfet_circuit/

File: tasks/page/makeReadme.js (hunk 2 above)
Comment (SDBowen) [reply tasks/page/makeReadme.js]: Good point; that wasn't the best choice.

I will change it to `https://github.com`

File: tasks/page/makeReadme.js (hunk 1 above)
Comment (SDBowen) [reply tasks/page/makeReadme.js]: https://github.com/kitspace/kitspace/pull/195/files#diff-061cabbd89c63bee0b066d3037b187c2R70-R71

Removed the image file type from the blob url check. Also took out the `/master/` match, as you could also point to a specific branch. I think this would be very rare though.

File: tasks/page/makeReadme.js (hunk 3 above)
Comment (SDBowen) [reply tasks/page/makeReadme.js]: Done.

**Comment by SDBowen** [comment]
Update building now. Should build as expected now! :crossed_fingers:

File: tasks/page/makeReadme.js [hunk 4]
```diff
@@ -10,40 +10,49 @@ const converter = new htmlToJsx({createClass: true, outputClassName: 'Readme'})
...
       deps.push(readmes[0])
     }
+
     const targets = [`build/.temp/${folder}/readme.jsx`]
+
+    if (folders.length > 4) {
+      const projectPath = folders.splice(4).join('/')
+      targets.push(projectPath)
+    }
+
```
Comment (kasbah) [inline tasks/page/makeReadme.js]: Is this the best way to detect `multi` repos? We should at least explain it in a comment.

File: tasks/page/makeReadme.js [hunk 5]
```diff
@@ -10,40 +10,49 @@ const converter = new htmlToJsx({createClass: true, outputClassName: 'Readme'})
...
+    let markdown = ''
+
     if (path.extname(readme).toLowerCase() === '.rst') {
       markdown = rst2mdown(contents)
+    } else {
+      markdown = contents
     }
+
+    if (info.repo.includes('https://github.com')) {
+      markdown = replaceBlobUrls(markdown)
```
Comment (kasbah) [inline tasks/page/makeReadme.js]: I don't think we want to replace _all_ blob urls.

File: tasks/page/makeReadme.js (hunk 4 above)
Comment (SDBowen) [reply tasks/page/makeReadme.js]: Added a comment for now, but I think it can be done better. 

I have used this same logic in a few others places, after this gets merged, I can make another PR changing all instances to a better approach.

File: tasks/page/makeReadme.js (hunk 5 above)
Comment (SDBowen) [reply tasks/page/makeReadme.js]: Another update to correct this.

File: tasks/page/makeReadme.js [hunk 6]
```diff
@@ -68,19 +65,25 @@ function addSpacing(string) {
...
+  const imagePath = /(!\[.*?]\()(.+?(\.png|\.jpg|\.gif|\.jpeg|\.bmp))/gi
 
-  return string.replace(imagePath, (_match, imgTag, path) => {
-    const parts = path.split('/')
-    const fileName = parts[parts.length - 1]
+  return string.replace(imagePath, (match, imgTag, path) => {
+    if (match.includes('/blob/')) return replaceBlobUrls(match)
 
-    return `${imgTag}/${projectPath}/${fileName}`
+    if (projectPath) return addProjectPath(imgTag, path, projectPath)
```
Comment (kasbah) [inline tasks/page/makeReadme.js]: Minor style stuff: 

- I never use if statements without brackets

Extra minor: 
- Commit messages always start with a capital

File: tasks/page/makeReadme.js (hunk 4 above)
Comment (kasbah) [reply tasks/page/makeReadme.js]: I think the comment and the variable naming could be a bit clearer, mentioning `multi` explicitly.

File: tasks/page/makeReadme.js (hunk 6 above)
Comment (kasbah) [reply tasks/page/makeReadme.js]: More importantly: are these two really exclusive. I.e. "blob" or "project relative", never both?

Comment (SDBowen) [reply tasks/page/makeReadme.js]: I don't believe so. Because we are looking at each match, it will either be a direct link (with a `blob`) or the image filename (we then add the path).

Comment (SDBowen) [reply tasks/page/makeReadme.js]: Not sure why I stopped using a capital on the commit messages. Will fix those.
